#ifndef WORKOUT_TYPE_H
#define WORKOUT_TYPE_H
/* workout type */
enum WORKOUT_TYPE
{
    WORKOUT_NONE = 0,
    WORKOUT_OUTDOOR_CYCLING = 21, //0
    WORKOUT_INDOOR_CYCLING = 22,  //1
    WORKOUT_OUTDOOR_RUN = 31,     //2
    WORKOUT_INDOOR_RUN = 32,      //3
    WORKOUT_SWIMMING = 42,        //5
    WORKOUT_HIKING = 51,          //6
    WORKOUT_ELLIPTICAL = 62,      //9
    WORKOUT_OUTDOOR_WLAK = 71,    //10
    WORKOUT_TRAIL_RUN = 81,       //12
    WORKOUT_SPINNING_BIKE = 91,   //14
    WORKOUT_OTHER_TYPE = 100,     //15
    WORKOUT_ROWING = 101,
    WORKOUT_JUMP_ROPE = 102,
    WORKOUT_SKIING = 103,
    WORKOUT_SNOWBOARD = 104,
    WORKOUT_SKI_CROSS_COUNTRY = 105,
    WORKOUT_GOLF = 106,
    WORKOUT_BASEBALL = 107,
    WORKOUT_SOCCER = 108,
    WORKOUT_RUNNING_STANCE = 109,
    WORKOUT_BADMINTON = 110,
    WORKOUT_TENNIS = 111,
    WORKOUT_SQUASH = 112,
    WORKOUT_TABLE_TENNIS = 113,
    WORKOUT_CRICKET = 114,
    WORKOUT_BOXING = 115,
    WORKOUT_DUMBBELL = 116,
    WORKOUT_BASKETBALL = 117,
    WORKOUT_YOGA = 118,
    WORKOUT_CMJ_PREDICT = 119,
    WORKOUT_STATIC_BALANCE = 120,
    WORKOUT_BODYWEIGHT_TRAINING = 121,
    WORKOUT_FRISBEE = 122,
    WORKOUT_OUTDOOR_CYCLING_FOOT = 1021,
    WORKOUT_INDOOR_CYCLING_FOOT = 1022,
    WORKOUT_OUTDOOR_RUN_FOOT = 1031,
    WORKOUT_INDOOR_RUN_FOOT = 1032,
    WORKOUT_WORKOUT_TYPE_END = 30,
};

enum BODYWEIGHT_TRAINING_TYPE
{
    // countable
    BODYWEIGHT_TRAINING_TYPE_START,
    
    BODYWEIGHT_TRAINING_PUSH_UP,
    BODYWEIGHT_TRAINING_CURL_UP,
    BODYWEIGHT_TRAINING_SQUAT,
    BODYWEIGHT_TRAINING_MOUNTAIN_CLIMBER,
    BODYWEIGHT_TRAINING_ANKLE_HOP,
    BODYWEIGHT_TRAINING_LV1_BICYCLE_CRUNCH,
    BODYWEIGHT_TRAINING_QUARTER_SQUAT_JUMP,
    BODYWEIGHT_TRAINING_SIT_UP,
    BODYWEIGHT_TRAINING_BURPEE_W_PUSH_UP,
    BODYWEIGHT_TRAINING_BURPEE,
    BODYWEIGHT_TRAINING_LV2_BICYCLE_CRUNCH,
    BODYWEIGHT_TRAINING_HIGH_KNEE,
    BODYWEIGHT_TRAINING_REPEAT_JUMPING,
    BODYWEIGHT_TRAINING_CYCLE_SPLIT_SQUAT,
    BODYWEIGHT_TRAINING_PLYOMETRIC_PUSH_UP,
    BODYWEIGHT_TRAINING_V_UP,
    BODYWEIGHT_TRAINING_SINGLE_LEG_PUSH_UP,
    BODYWEIGHT_TRAINING_JUMPING_JACK,

    BODYWEIGHT_TRAINING_TYPE_END,
};


#endif
